---
info:
  app:
    title: Patient Service
    description: Service for storing and maintaining patient records.

logging:
  level:
    uk.com.poodle: DEBUG

server:
  port: 8082

service:
  mail:
    from: poodle@harhay.co.uk
  scheduler:
    appointment-reminder:
      cron: 0 0 8 * * *

spring:
  application:
    name: patient-service
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: select 1
      maximum-pool-size: 10
      minimum-idle: 1
    url: jdbc:postgresql://TODO
    username: TODO
    password: TODO
  flyway:
    baseline-on-migrate: false
    enabled: true
    url: ${spring.datasource.url}
    user: TODO
    password: TODO
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
