---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    username: patient_service_rw
    password: patient_service_rw
  flyway:
    baseline-on-migrate: true
    user: patient_service_admin
    password: patient_service_admin

# Profile for debugging hibernate
---
spring.config.activate.on-profile: debug-hibernate

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.cache: debug
    org.hibernate.search: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
